In [15]:
import numpy as np


In [16]:
np.__version__

'2.2.3'

In [17]:
np.array([1, 2, 3]), type(np.array([1, 2, 3]))

(array([1, 2, 3]), numpy.ndarray)

In [18]:
np.array([1, 2, 3, "hello"])

array(['1', '2', '3', 'hello'], dtype='<U21')

In [19]:
array = np.array([1, 2, 3], dtype=np.int8)
array, array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [20]:
bin(2**8)

'0b100000000'

In [21]:
bin(2**8-1)

'0b11111111'

In [22]:
array = np.array([1, 2, 3, 127, -128],dtype=np.int8)
array

array([   1,    2,    3,  127, -128], dtype=int8)

In [24]:
array = np.array([1, 2, 3, 128, 255],dtype=np.int8)
array

OverflowError: Python integer 128 out of bounds for int8