In [41]:
import numpy as np

In [42]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
np.arange(7, 15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
np.arange(7, 15, 3)

array([ 7, 10, 13])

In [45]:
np.arange(range(7, 15, 3))

TypeError: unsupported operand type(s) for -: 'range' and 'int'