In [44]:
import numpy as np


In [45]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [46]:
array.min(), array.max()

(np.int64(10), np.int64(500))

In [47]:
array.sum(), sum(array)

(np.int64(1338), np.int64(1338))

In [48]:
array.mean()

np.float64(111.5)

In [49]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.max(), array.argmax()

(np.int64(500), np.int64(2))

In [50]:
array[array > 100]

array([500, 310, 101, 203])

In [51]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [52]:
array[-1]

np.int64(30)

In [53]:
array[-2:]

array([203,  30])

In [54]:
array[array% 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [55]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [56]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [57]:
array[(array % 3 == 0) | (array < 40)]

array([23, 10, 30, 20, 30, 30])