In [37]:
 #este bisect daca
#  1. este divizibil cu 400
#  2. este divizibil cu 4, dar nu cu 100

In [38]:
start_year = 1899
stop_year = 2025

In [39]:
import numpy as np

In [40]:
array = np.array([1899, 2025])
array

array([1899, 2025])

In [41]:
array = np.arange(start_year, stop_year)

In [42]:
array[(array % 4 == 0) & (array % 100 != 0)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024])

In [43]:
array[(array % 400 == 0) | (array % 4 == 0) & (array % 100 != 0)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])

In [45]:
divizibile_cu_400 = array % 400 == 0
divizibile_cu_4 = array % 4 == 0
nedivizibile_cu_100 = array % 100 != 0

array[divizibile_cu_400 | (divizibile_cu_4 & nedivizibile_cu_100)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])